<a href="https://colab.research.google.com/github/sardormamatqobulov1/NumPy_YouTube/blob/main/NumPy_Boolean_Arrays%2C_Sorting_%26_Set_Operations_YouTube.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

rng = np.random.default_rng()
arr = rng.standard_normal(100)
arr

array([-0.06615601, -0.61628883,  0.51225148, -0.06463959, -1.65350216,
        0.6594044 ,  0.4287927 , -1.51310653,  0.40144147, -1.75985128,
       -1.0126864 , -0.81633031,  0.05973458,  0.7034329 ,  0.85058632,
        0.03805197, -1.84270399, -0.81569264,  0.64287553, -0.49831939,
       -0.31673367,  1.76327193, -0.66849717,  2.24952501,  0.61831547,
        0.57056615,  0.09448182, -0.45347901, -0.07207703,  0.07492592,
       -0.53290925,  1.59356854,  1.29674114, -0.68042784,  0.06855548,
       -0.06393463,  0.89111987, -0.61886708,  0.07591006,  0.11751825,
       -0.97239962, -0.67843875,  0.5026309 ,  2.21753555, -1.04315714,
        0.0819525 ,  1.96011688, -0.12869517, -0.08706589,  0.05997701,
       -0.47576646,  0.77323576,  0.98098278,  0.95096321,  0.24678756,
       -0.31863241,  1.42592036,  0.8174148 ,  0.81065318,  1.11891076,
        2.44717377, -1.8062467 ,  1.84582707, -0.63626218, -0.80768466,
        0.71823984, -1.38356871,  0.14683499,  0.73457444, -1.84

In [ ]:
(arr > 0).sum() #Number of  positive values

np.int64(55)

In [ ]:
(arr <=0).sum() # Number of negative values

np.int64(45)

##any() and all()

In [ ]:
bools = np.array([False, False, True, False])

bools.any() #True
bools.all() #False

np.False_

##Sorting A 1D array

In [ ]:
arr = rng.standard_normal(10)
arr.sort()

In [ ]:
arr

array([-1.65244385, -1.10938805, -0.34205554, -0.27631751,  0.05600864,
        0.55209468,  0.69750213,  0.70592789,  0.99438254,  1.66305728])

In [ ]:
arr = rng.standard_normal((5,3))

In [ ]:
arr.sort(axis = 0)

In [ ]:
arr

array([[-1.08681296, -0.79419   , -0.82904015],
       [-0.82221056,  0.06278527, -0.25581948],
       [-0.58715378,  0.27703142,  0.41345582],
       [-0.02193578,  0.68195266,  0.53657347],
       [ 0.00456035,  1.17352794,  0.55953848]])

#np.sort()

In [ ]:
arr2 = np.array([5,-10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr)

In [ ]:
sorted_arr2

array([[-1.08681296, -0.82904015, -0.79419   ],
       [-0.82221056, -0.25581948,  0.06278527],
       [-0.58715378,  0.27703142,  0.41345582],
       [-0.02193578,  0.53657347,  0.68195266],
       [ 0.00456035,  0.55953848,  1.17352794]])

##Unique & Set Operations

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [ ]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

##np.in1d

In [ ]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

/tmp/ipython-input-1579217568.py:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2,3,6])


array([ True, False, False,  True,  True, False,  True])