<a href="https://colab.research.google.com/github/sardormamatqobulov1/NumPy_YouTube/blob/main/NumPy_Random_Numbers_%26_Ufuncs_YouTube.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pseudorandom Number
Generation

In [1]:
import numpy as np

In [2]:
samples = np.random.standard_normal((4,4))
samples

array([[-0.09888234, -1.77975192,  0.27619819, -0.5612071 ],
       [-0.97928141, -0.22313255, -1.5397996 , -0.36463044],
       [-1.2087136 , -0.3246106 ,  0.55590101,  0.26733858],
       [ 0.07983476,  1.82704748,  1.10416348,  0.6692935 ]])

In [3]:
#speed comparison
from random import normalvariate
N = 1_000_000

In [4]:
%timeit [normalvariate(0,1) for _ in range(N)]

1.46 s ± 427 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit np.random.standard_normal(N)

46 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
#Generator and Seed
rng = np.random.default_rng(seed=12345)
rng.standard_normal((2,3))

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [7]:
#Common methods
rng.integers(0, 10, size=5)
rng.uniform(0,1, size=5)

array([0.94180287, 0.24824571, 0.94888115, 0.66723745, 0.09589794])

##Universal Functions(ufuncs)

In [8]:
#Unary ufuncs
arr = np.arange(10)
np.sqrt(arr)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [9]:
#Binary ufuncs
x = rng.standard_normal(8)
y = rng.standard_normal(8)

np.maximum(x,y)

array([ 0.90291934, -0.06068952,  0.78884434,  0.44948393,  0.57585751,
        1.39897899,  1.72473993,  2.61815943])

In [10]:
#Multiple outputs
arr = rng.standard_normal(7) * 5
frac, whole = np.modf(arr)

In [11]:
#out parameter
out = np.zeros_like(arr)
np.add(arr, 1, out=out)

array([ 4.88680672,  5.14316598, -3.79494157, -5.04694143, -6.06146007,
        3.70773415,  4.75969698])