<a href="https://colab.research.google.com/github/sardormamatqobulov1/NumPy_YouTube/blob/main/NumpyYoutube.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##What is an ndarray?

In [21]:
import numpy as np

In [23]:
data = np.array([[1.5, -0.1, 3], [ 0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

##Why is NumPy so fast?

In [24]:
my_arr = np.arange(1_000_000)
my_arr *2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

##Creating NumPy arrays


In [26]:
np.array([1,2,3])

array([1, 2, 3])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Shape and dtype

In [31]:
data.shape

(2, 3)

In [32]:
data.dtype

dtype('float64')

##Vectorized arithmetic

In [33]:
arr = np.array([[1,2,3], [4,5,6]])

In [34]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [35]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
arr ** 3

array([[  1,   8,  27],
       [ 64, 125, 216]])

##Indexing and slicing

In [39]:
arr = np.arange(10)
arr[5:8]

array([5, 6, 7])

In [40]:
arr_slice = arr[5:8]

In [42]:
arr_slice[:] = 100

In [43]:
arr_slice

array([100, 100, 100])

In [44]:
arr[5:8].copy()

array([100, 100, 100])