<a href="https://colab.research.google.com/github/sardormamatqobulov1/NumPy_YouTube/blob/main/NumpyYoutube_continue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Indexing with Slices

In [30]:
import numpy as np

In [32]:
arr = np.array([0,1,2,3,4,64,64,64,8,9])
arr[1:6]

array([ 1,  2,  3,  4, 64])

##Slicing 2D Arrays(Rows & Columns)

In [34]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

##Slicing Rows and Columns Together

In [35]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

##Lower Dimensional Slices

In [36]:
arr2d[1, :2]

array([4, 5])

In [37]:
arr2d[:2,2]

array([3, 6])

##Using : to Select Entire AXis

In [38]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

##Asssigning Values to Slices

In [39]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

##Boolean Indexing

In [40]:
#Boolen index Basics
names = np.array(["Bob", "Joe","Will","Bob","Will","Joe","Joe"])
names == "Bob"

array([ True, False, False,  True, False, False, False])

##Using Boolean Array to Filter Data

In [42]:
data = np.array([[4,7], [0,2],[-5, 6],[0,0], [1,2],[-12,4], [3,4]])
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

##Setting Values Using Boolen Indexing

In [43]:
data[names == "Bob", 1]

array([7, 0])

In [44]:
#Not Operator
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,   4],
       [  3,   4]])

In [45]:
mask = (names == "Bob") | (names == "Will")
data[mask]
# &= and   | = or

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

##Setting Values Using Boolean Indexing


In [46]:
data [ data < 0] = 0
data
#

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 4],
       [3, 4]])

##Fancy Indexing(Integer Arrays)

In [47]:
arr = np.zeros((8,4))

for i in range(8):
  arr[i] = i

arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [48]:
#Negative index example
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

##Selecting Specific Elements

In [49]:
arr = np.arange(32).reshape((8,4))
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

##Rectangular Selection with Fancy Indexing

In [50]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

##Transpose Arrays with .T

In [51]:
arr = np.arange(15).reshape((3,5))
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

##Matrix Multiplication


In [52]:
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

##Swapping Axes

In [53]:
arr.swapaxes(0,1)
#

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])