<a href="https://colab.research.google.com/github/sardormamatqobulov1/NumPy_YouTube/blob/main/Simulating_Many_Random_Walks_at_Once_YouTube.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
rng = np.random.default_rng()

##Setup:Number of Walks and Steps

In [23]:
nwalks = 5000
nsteps = 1000

##Generate Random Steps(2D)

In [24]:
draws = rng.integers(0,2,size=(nwalks,nsteps))

In [25]:
draws

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 1, 0]])

##Convert Coin Flips to Steps

In [26]:
steps = np.where(draws > 0, 1, -1)

In [27]:
steps

array([[-1, -1, -1, ..., -1, -1, -1],
       [ 1, -1, -1, ...,  1,  1,  1],
       [ 1, -1,  1, ..., -1,  1,  1],
       ...,
       [ 1,  1,  1, ..., -1, -1, -1],
       [ 1, -1,  1, ..., -1, -1,  1],
       [ 1, -1,  1, ..., -1,  1, -1]])

##Compute All Walks at Once

In [28]:
walks = steps.cumsum(axis=1)

In [29]:
walks

array([[ -1,  -2,  -3, ..., -14, -15, -16],
       [  1,   0,  -1, ..., -12, -11, -10],
       [  1,   0,   1, ...,  30,  31,  32],
       ...,
       [  1,   2,   3, ...,  50,  49,  48],
       [  1,   0,   1, ..., -20, -21, -20],
       [  1,   0,   1, ...,   2,   3,   2]])

##Global Max&Min

In [30]:
walks.max()

np.int64(111)

In [31]:
walks.min()

np.int64(-126)

##Who Reached ±30?

In [32]:
hits30 = (np.abs(walks) >= 30).any(axis=1)

In [34]:
hits30.sum()

np.int64(3456)

##Crossing Time(Important Concept)

In [35]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)

In [36]:
crossing_times

array([357, 541, 413, ..., 449, 159,  93])

##Average Crossing Time

In [37]:
crossing_times.mean()

np.float64(502.1302083333333)

##Different Step Distribution

In [38]:
draws = 0.25 * rng.standard_normal((nwalks, nsteps))

In [39]:
draws

array([[ 0.28008037, -0.09089913, -0.03380413, ...,  0.09593648,
         0.03537628, -0.32929646],
       [ 0.36566011,  0.15282329, -0.17359056, ..., -0.47352337,
        -0.36512138,  0.77658648],
       [ 0.01539567, -0.01442952,  0.27240599, ..., -0.04703608,
        -0.29712735,  0.16927725],
       ...,
       [ 0.1892563 , -0.16082501,  0.33037836, ..., -0.38415135,
         0.00863214,  0.05300656],
       [-0.18908815, -0.14841545, -0.19091975, ..., -0.05051315,
         0.16134626,  0.10382501],
       [ 0.33703762,  0.03636201,  0.09360075, ...,  0.16282809,
        -0.04774827, -0.10851595]])